### ISSUE TITLE
[SpeakUp] Bad value found for "ANYPAWN_nameIndef"

### ISSUE THREAD

**Issue by sergiodinapoli** [jptrrs/SpeakUp#1]
Desde a ultima atualizaçao, surge isto independente de outros fatores, pelo que vi.
No mais, funciona. Mas o erro é assinalado.

[SpeakUp] Bad value found for "ANYPAWN_nameIndef"
Constants are: null
Rules are: System.Collections.Generic.List`1[Verse.Grammar.GrammarResolver+RuleEntry], System.Collections.Generic.List`1[Verse.Grammar.GrammarResolver+RuleEntry], System.Collections.Generic.List`1[Verse.Grammar.GrammarResolver+RuleEntry], System.Collections.Generic.List`1[Verse.Grammar.GrammarResolver+RuleEntry], System.Collections.Generic.List`1[Verse.Grammar.GrammarResolver+RuleEntry], System.Collections.Generic.List`1[Verse.Grammar.GrammarResolver+RuleEntry], System.Collections.Generic.List`1[Verse.Grammar.GrammarResolver+RuleEntry], System.Collections.Generic.List`1[Verse.Grammar.GrammarResolver+RuleEntry], System.Collections.Generic.List`1[Verse.Grammar.GrammarResolver+RuleEntry], System.Collections.Generic.List`1[Verse.Grammar.GrammarResolver+RuleEntry], System.Collections.Generic.List`1[Verse.Grammar.GrammarResolver+RuleEntry], System.Collections.Generic.List`1[Verse.Grammar.GrammarResolver+RuleEntry], System.Collections.Generic.List`1[Verse.Grammar.GrammarResolver+RuleEntry], System.Collections.Generic.List`1[Verse.Grammar.GrammarResolver+RuleEntry], System.Collections.Generic.List`1[Verse.Grammar.GrammarResolver+RuleEntry], System.Collections.Generic.List`1[Verse.Grammar.GrammarResolver+RuleEntry], System.Collections.Generic.List`1[Verse.Grammar.GrammarResolver+RuleEntry], System.Collections.Generic.List`1[Verse.Grammar.GrammarResolver+RuleEntry], System.Collections.Generic.List`1[Verse.Grammar.GrammarResolver+RuleEntry], System.Collections.Generic.List`1[Verse.Grammar.GrammarResolver+RuleEntry], System.Collections.Generic.List`1[Verse.Grammar.GrammarResolver+RuleEntry], System.Collections.Generic.List`1[Verse.Grammar.GrammarResolver+RuleEntry], System.Collections.Generic.List`1[Verse.Grammar.GrammarResolver+RuleEntry], System.Collections.Generic.List`1[Verse.Grammar.GrammarResolver+RuleEntry], System.Collections.Generic.List`1[Verse.Grammar.GrammarResolver+RuleEntry], System.Collections.Generic.List`1[Verse.Grammar.GrammarResolver+RuleEntry], System.Collections.Generic.List`1[Verse.Grammar.GrammarResolver+RuleEntry], System.Collections.Generic.List`1[Verse.Grammar.GrammarResolver+RuleEntry], System.Collections.Generic.List`1[Verse.Grammar.GrammarResolver+RuleEntry], System.Collections.Generic.List`1[Verse.Grammar.GrammarResolver+RuleEntry], System.Collections.Generic.List`1[Verse.Grammar.GrammarResolver+RuleEntry], System.Collections.Generic.List`1[Verse.Grammar.GrammarResolver+RuleEntry], System.Collections.Generic.List`1[Verse.Grammar.GrammarResolver+RuleEntry], System.Collections.Generic.List`1[Verse.Grammar.GrammarResolver+RuleEntry], System.Collections.Generic.List`1[Verse.Grammar.GrammarResolver+RuleEntry], System.Collections.Generic.List`1[Verse.Grammar.GrammarResolver+RuleEntry], System.Collections.Generic.List`1[Verse.Grammar.GrammarResolver+RuleEntry], System.Collections.Generic.List`1[Verse.Grammar.GrammarResolver+RuleEntry], System.Collections.Generic.List`1[Verse.Grammar.GrammarResolver+RuleEntry], System.Collections.Generic.List`1[Verse.Grammar.GrammarResolver+RuleEntry], System.Collections.Generic.List`1[Verse.Grammar.GrammarResolver+RuleEntry], System.Collections.Generic.List`1[Verse.Grammar.GrammarResolver+RuleEntry], System.Collections.Generic.List`1[Verse.Grammar.GrammarResolver+RuleEntry], System.Collections.Generic.List`1[Verse.Grammar.GrammarResolver+RuleEntry], System.Collections.Generic.List`1[Verse.Grammar.GrammarResolver+RuleEntry], System.Collections.Generic.List`1[Verse.Grammar.GrammarResolver+RuleEntry], System.Collections.Generic.List`1[Verse.Grammar.GrammarResolver+RuleEntry], System.Collections.Generic.List`1[Verse.Grammar.GrammarResolver+RuleEntry], System.Collections.Generic.List`1[Verse.Grammar.GrammarResolver+RuleEntry], System.Collections.Generic.List`1[Verse.Grammar.GrammarResolver+RuleEntry], System.Collections.Generic.List`1[Verse.Grammar.GrammarResolver+RuleEntry], System.Collections.Generic.List`1[Verse.Grammar.GrammarResolver+RuleEntry], System.Collections.Generic.List`1[Verse.Grammar.GrammarResolver+RuleEntry], System.Collections.Generic.List`1[Verse.Grammar.GrammarResolver+RuleEntry]

Verse.Log:Error(String, Boolean)
SpeakUp.GrammarResolver_RandomPossiblyResolvableEntry:Prefix(String, Dictionary`2, List`1, List`1, Dictionary`2, RuleEntry&)
Verse.Grammar.GrammarResolver:Verse.Grammar.GrammarResolver.RandomPossiblyResolvableEntry_Patch2(String, Dictionary`2, List`1, List`1)
Verse.Grammar.GrammarResolver:Verse.Grammar.GrammarResolver.TryResolveRecursive_Patch2(RuleEntry, Int32, Dictionary`2, String&, Boolean, List`1, List`1)
Verse.Grammar.GrammarResolver:Verse.Grammar.GrammarResolver.TryResolveRecursive_Patch2(RuleEntry, Int32, Dictionary`2, String&, Boolean, List`1, List`1)
Verse.Grammar.GrammarResolver:ResolveUnsafe(String, GrammarRequest, Boolean&, String, Boolean, Boolean, List`1, List`1, Boolean)
Verse.Grammar.GrammarResolver:ResolveUnsafe(String, GrammarRequest, String, Boolean, Boolean, List`1, List`1, Boolean)
Verse.Grammar.GrammarResolver:Verse.Grammar.GrammarResolver.Resolve_Patch1(String, GrammarRequest, String, Boolean, String, List`1, List`1, Boolean)
RimWorld.TaleTextGenerator:GenerateTextFromTale(TextGenerationPurpose, Tale, Int32, RulePackDef)
RimWorld.TaleReference:GenerateText(TextGenerationPurpose, RulePackDef)
RimWorld.CompArt:GenerateTitle()
RimWorld.CompArt:InitializeArt(Thing, ArtGenerationContext)
RimWorld.CompArt:InitializeArt(ArtGenerationContext)
RimWorld.CompQuality:SetQuality(QualityCategory, ArtGenerationContext)
Verse.PawnGenerator:PostProcessGeneratedGear(Thing, Pawn)
RimWorld.PawnWeaponGenerator:TryGenerateWeaponFor(Pawn, PawnGenerationRequest)
Verse.PawnGenerator:GenerateGearFor(Pawn, PawnGenerationRequest)
Verse.PawnGenerator:TryGenerateNewPawnInternal(PawnGenerationRequest&, String&, Boolean, Boolean)
Verse.PawnGenerator:GenerateNewPawnInternal(PawnGenerationRequest&)
Verse.PawnGenerator:GenerateOrRedressPawnInternal(PawnGenerationRequest)
Verse.PawnGenerator:GeneratePawn(PawnGenerationRequest)
RimWorld.Faction:TryGenerateNewLeader()
RimWorld.FactionGenerator:NewGeneratedFaction(FactionDef)
RimWorld.FactionGenerator:GenerateFactionsIntoWorld()
RimWorld.Planet.WorldGenStep_Factions:GenerateFresh(String)
RimWorld.Planet.WorldGenerator:GenerateWorld(Single, String, OverallRainfall, OverallTemperature, OverallPopulation)
Verse.Root_Play:Verse.Root_Play.SetupForQuickTestPlay_Patch0()
Verse.<>c:<Start>b__1_2()
Verse.LongEventHandler:RunEventFromAnotherThread(Action)
Verse.<>c:<UpdateCurrentAsynchronousEvent>b__27_0()
System.Threading.ThreadHelper:ThreadStart_Context(Object)
System.Threading.ExecutionContext:RunInternal(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object)
System.Threading.ThreadHelper:ThreadStart()

**Comment by jptrrs** [comment]
Aê! Agora sim, estamos caçando bugs direito! Sim, é isso que precisamos. Exceto que quando você diz "surge isto" eu não faço idéia de em que momento o erro aconteceu.... Ter o link pro log do HugsLib também ajuda bem (CTRL+F12).
Mas não se preocupe com esse em particular, porque é uma mensagem de erro que eu mesmo programei e que posso dizer com toda certeza que é inofensiva. O intuito é avisar quando tiver algo digitado errado no XML. Só q essa checagem tá rodando no momento errado, pq é normal ter keywords inválidas na inicialização do jogo. Eu achei que já tinha prevenido o alerta de aparecer nessa hora, mas obviamente a limitação que eu coloquei não foi suficiente. Já corrigi, o alerta vai se comportar a partir da próxima atualização.
