### ISSUE TITLE
Social fight: na hora da briga, gera aviso vermelho

### ISSUE THREAD

**Issue by sergiodinapoli** [jptrrs/SpeakUp#13]
Uma pawn (Rena) tava em Insulting Spree, soltando xingamentos.
Ragnar, a vitima, reagiu e deu nela. Nesse momento, surgiu:

Exception ticking Ragnar (at (127, 0, 130)): System.NullReferenceException: Object reference not set to an instance of an object

https://gist.github.com/c0a957fbbd1a86eaa9338ca82c2ec5d5
[test.zip](https://github.com/jptrrs/SpeakUp/files/6572773/test.zip)

Me lembra de um velho bug resolvido, onde dar dano nos outros dava erro vermelho. Mas voce matou esse erro, nunca mais teve.

**Comment by jptrrs** [comment]
Então, ficou faltando só vc se dar ao trabalho de tentar reproduzir para poder me dizer como... Eu consegui assim:

1. Quickstart um nova colônia,
2. Spawn a colonist (pq parece que sem ter relações com os existentes fica mais provavel eles brigarem)
3. Mental state, insulting spree no novato.
4. Restringe todos a uma área pequena.
5. Espera a briga começar.

Daí com isso eu consegui isolar o problema. Resolvi com uma condicional para o parêmetro que retorna a atividade atual.
