### ISSUE TITLE
Exception ticking Bullet_BoltActionRifle235716: System.NullReferenceException

### ISSUE THREAD

**Issue by sergiodinapoli** [jptrrs/SpeakUp#14]
https://gist.github.com/619371244f148611335509750cf74e6c

Erro vermelho:
(https://github.com/jptrrs/SpeakUp/files/6605649/test.zip): Object reference not set to an instance of an object
  at SpeakUp.ExtraGrammarUtility+<ExtraRulesForPawn>d__7.MoveNext () [0x000b3] in <096fa554ada04b2c86b6de592215ed59>:0 

Savegame em seguida.

Estava dando tiro de boas em um raider.

**Comment by sergiodinapoli** [comment]
[test.zip](https://github.com/jptrrs/SpeakUp/files/6605650/test.zip)

**Comment by jptrrs** [comment]
Como sempre, vc pulou o passo 4 do "Bug Reporting" do seu próprio mod: https://steamcommunity.com/workshop/filedetails/discussion/2502518544/3113656428090982300/
O que acontece casulamente, Sérgio, NUNCA interessa.

**Comment by jptrrs** [comment]
Como reproduz?
Além disso, não consigo abrir o save porque você não seguiu o passo 4 do seu próprio "BUG REPORTING": https://steamcommunity.com/workshop/filedetails/discussion/2502518544/3113656428090982300/

**Comment by sergiodinapoli** [comment]
Respondendo tb ao outro issue sobre o ponto 4:
entao a partir de agora na hora de testar vou usar apenas
Core, Royals, SpeakUp e seus requisitos.

Tem algum mod extra que voce autoriza, entre os QoL, ou melhor ficar nesse minimo dos minimos mesmo?

**Comment by sergiodinapoli** [comment]
Como reproduz? Dando tiro no raider :-)
Mas se vc nao consegue abrir o save, ai complica... Entendi.

**Comment by jptrrs** [comment]
> 
> 
> Respondendo tb ao outro issue sobre o ponto 4:
> entao a partir de agora na hora de testar vou usar apenas
> Core, Royals, SpeakUp e seus requisitos.
> 
> Tem algum mod extra que voce autoriza, entre os QoL, ou melhor ficar nesse minimo dos minimos mesmo?

E por acaso existe algum mod que esteja 100% livre de causar intereferência?

**Comment by sergiodinapoli** [comment]
Nao, mas por outro lado voce (se lembra?) me disse "Pode usar mods de leve, tipo OTW, List everything...".
Provavelmente voce na época quis dizer: "Pode usar mods de leve, tipo OTW, List everything... EXCETO em fase de testing".
:-D

**Comment by jptrrs** [comment]
> 
> 
> Nao, mas por outro lado voce (se lembra?) me disse "Pode usar mods de leve, tipo OTW, List everything...".
> Provavelmente voce na época quis dizer: "Pode usar mods de leve, tipo OTW, List everything... EXCETO em fase de testing".
> :-D

A partir do momento que o mod é obrigatório para abrir um save feito com ele, já não é "de leve" mais.
É muito fácil entender o que é preciso para reportar um issue, Sérgio, é só você se colocar no meu lugar! rsrsrsrs
