### ISSUE TITLE
1 chitchat, 2 respostas

### ISSUE THREAD

**Issue by sergiodinapoli** [jptrrs/SpeakUp#15]
https://gist.github.com/c40df41a2c9f5480a1e85ed3402942d2

[test2respostas.zip](https://github.com/jptrrs/SpeakUp/files/6605812/test2respostas.zip)

Teste que acaba de começar.
Assim que o test começou, tranquei todo mundo num quadrado "home".
Botei todo mundo forçado com joygiver do tipo skygazer, de manha ou tarde (tem que ter o jobText "cloudwatching.")

Tudo corre bem: Mal fala, Miracles responde... MAS
Mal, inesperadamente, reage usando uma InteractionDef do Interactions.xml, quando era para ficar calado.

Logo em seguida (no save, isso ainda nao aconteceu, mas acontece poco depois), o Miracles também solta uma resposta inesperada, de novo sem nenhum chitchat inicial ao qual reagir.

Nisso tudo o 3° cara fica na dele.

As frases usadas sao as primeiras do XML de respostas.

Prosseguindo no save, estou achando que o sistema fica louco quando há muitas coisas programadas para o mesmo tick. E ai algo se perde, ou fica programado numa sequencia temporal que gera uma impressao de caos.

Esse save que mandei, acho, pode ser bem util pois é so apertar play e ver o circo pegando fogo :-D

**Comment by jptrrs** [comment]
Não consigo abrir o save porque você não seguiu o passo 4 do seu próprio "BUG REPORTING": https://steamcommunity.com/workshop/filedetails/discussion/2502518544/3113656428090982300/

**Comment by sergiodinapoli** [comment]
https://gist.github.com/b86e9be82656f799bd98e7cee8476eeb

[test0706.zip](https://github.com/jptrrs/SpeakUp/files/6610785/test0706.zip)

Agora é zero mod desnecessario.
Apenas nao saberia dizer como reproduzir o problema. A "repetinte" tava mineirando, mas nao sei se isso é util.
Isso de reproduzi, é osso. :-)

Mas pelo menos isso que estou inviando seria util para recolher detalhes, para futuro uso investigativo?

Por exemplo (tentei investigar sozinho, mas fiquei perdidaço no savegame), sera' que daria para confirmar se foi isto que rolou?

Tick 1 - Um cara P1 solta um chitchat para outro cara P2; a resposta fica programada para Tick 2
Tick 2 - 
-P1 solta um chitchat para P2; a resposta fica programada para Tick 3; 
-P2 responde a P1, (pois foi cutucado no Tick1)

Devido a muita coisa acontecendo no Tick2 ao mesmo tempo, o chitchat ativado por P1 "se perde no caminho" e adeus, nao é visualizado.

Ai o que a gente ve na tela é: 
Tick1-P1 soltando um chitchat
Tick2-P2 respondendo
Tick3-P2 respondendo

Estou viajando pra Uranus ou... talvez falei algo plausivel? :-D

**Comment by jptrrs** [comment]
> Isso de reproduzi, é osso.

Pra você ver a encrenca que vc tá passando pros outros quando não existe esse cuidado.

> Por exemplo (tentei investigar sozinho, mas fiquei perdidaço no savegame), sera' que daria para confirmar se foi isto que rolou?

Não encontrei nenhuma fala repetida no log. Se você abrir o arquivo e procurar pelo "playLog", pode conferir por si mesmo.

Mais uma vez, não dá pra reproduzir e não tem nenhuma evidência, portanto não é um issue.
Além disso, em se tratando falas repetidas, já tem um outro aberto, o #11 (vou até editar o nome dele para deixar claro),  então estou fechando esse aqui.
