### ISSUE TITLE
Caravana/seated (?)

### ISSUE THREAD

**Issue by sergiodinapoli** [jptrrs/SpeakUp#16]
https://gist.github.com/ff72971020b0c540467e7556463826d4
[test_caravan.zip](https://github.com/jptrrs/SpeakUp/files/6625273/test_caravan.zip)
https://ibb.co/pdXhm48 (<=== esse foi fornecido por um usuario que acenou ao erro)

Acho que dessa vez fiz tudo direitim mesmo :-)

1. ninguem falou disso antes
2. tem savegame quentinho
3. versao mais recente de tudo
4. basta criar e enviar qualquer caravana, que o trem acontece quando voce abre o social tab // modlist minimalista

No meu log nao consigo enxergar a referencia ao parametro "seated" indicado na imagem solta do ibb.co .

**Comment by jptrrs** [comment]
Fixed for v.0.6
