### ISSUE TITLE
Object reference not set to an instance of an object   at SpeakUp.ExtraGrammarUtility

### ISSUE THREAD

**Issue by sergiodinapoli** [jptrrs/SpeakUp#24]
https://gist.github.com/17555a99f621292be28e56fd014539bd
[20210619.zip](https://github.com/jptrrs/SpeakUp/files/6681017/20210619.zip)

Manatee will generate a red error as soon as his gun hits Delgado.
I tried it 3 times, 3 times it happened.

**Comment by sergiodinapoli** [comment]
I just noticed that when this happens, all social/combat log is deleted for every pawn, and no new log content is generated.
Yet, bubbles show up as expected.

**Comment by jptrrs** [comment]
Some step must be missing, because I get no errors.
(except the one from Camera+)
![noError](https://user-images.githubusercontent.com/47060670/122650173-c2510d00-d107-11eb-90bf-f0ee6d78cdaf.png)

**Comment by 5katz** [comment]
Can confirm, Seems to cause Bullet Ticking error on impact, and breaks combat logs and social tabs!

To JPT, I had to reload once for the bullet error to trigger, so maybe test multiple times, and see if it is triggered then, if not, i have a log with the error here: https://pastebin.com/nHESttNf

didnt have the game open anymore so its not a hugslog directly, but the player log none the less.

**Comment by sergiodinapoli** [comment]
@jptrrs 
I loaded 5 times. 
It happened 4 times out of 5.

Also, even if it does not happen, Isoldina will eventually catch up and most probably cause the bug via her plasteel dagger in Delgado's back.

**Comment by jptrrs** [comment]
Fixed for v.0.6.
NOTE: unsolved log entries will still show as such at the log. But at least they won't cause the UI to fail!
