### ISSUE TITLE
Social tab + Log Grammar Resolution

### ISSUE THREAD

**Issue by sergiodinapoli** [jptrrs/SpeakUp#25]
Problem:
when you open and keep open Social tab with Log Grammar Resolution activated, the game gets laggy and the log fills up with spam.

I'm not sending savegame and log because you can easily cause this bug at will, you just need to open the Social tab with Log Grammar Resolution activated.

**Comment by jptrrs** [comment]
Solution: only use Log Grammar Resolution when really needed! ;-)
