### ISSUE TITLE
Strange wood related red warnings

### ISSUE THREAD

**Issue by sergiodinapoli** [jptrrs/SpeakUp#3]
The same with LumberOak.
WoodLog_Teak is reported twice.

I used a new, very different test scenario. I can't understand how is it possible that the game still looks for this special woods, when I took away all the wood-related mods.

Could not load reference to Verse.ThingDef named WoodLog_Teak
Verse.Log:Error(String, Boolean)
Verse.ScribeExtractor:DefFromNode(XmlNode)
Verse.Scribe_Defs:Look(ThingDef&, String)
RimWorld.ScenPart_ThingCount:ExposeData()
Verse.ScribeExtractor:SaveableFromNode(XmlNode, Object[])
Verse.Scribe_Collections:Look(List`1&, Boolean, String, LookMode, Object[])
Verse.Scribe_Collections:Look(List`1&, String, LookMode, Object[])
RimWorld.Scenario:ExposeData()
Verse.ScribeExtractor:SaveableFromNode(XmlNode, Object[])
Verse.Scribe_Deep:Look(Scenario&, Boolean, String, Object[])
Verse.Scribe_Deep:Look(Scenario&, String, Object[])
Verse.GameDataSaveLoader:TryLoadScenario(String, ScenarioCategory, Scenario&)
RimWorld.ScenarioFiles:RecacheData()
RimWorld.ScenarioLister:RecacheData()
RimWorld.ScenarioLister:RecacheIfDirty()
RimWorld.<AllScenarios>d__1:MoveNext()
System.Linq.Enumerable:TryGetFirst(IEnumerable`1, Func`2, Boolean&)
System.Linq.Enumerable:FirstOrDefault(IEnumerable`1, Func`2)
HugsLib.Quickstart.QuickstartController:TryGetScenarioByName(String)
HugsLib.Quickstart.QuickstartController:PrepareMapGeneration()
HugsLib.Quickstart.QuickstartController:InitateMapGeneration()
HugsLib.Quickstart.QuickstartController:InitiateQuickstart()
Verse.LongEventHandler:UpdateCurrentSynchronousEvent(Boolean&)
Verse.LongEventHandler:LongEventsUpdate(Boolean&)
Verse.Root:Verse.Root.Update_Patch1(Root)
Verse.Root_Entry:Update()

**Comment by jptrrs** [comment]
Not related to Speakup.... But I'll try to help.
Except, once again, I can't tell when it happened! Can you explain? Also,
please include the full game log (Ctrl+F12).
Why are we talking in english?
Thanks.

João Pedro

**Comment by sergiodinapoli** [comment]
Acontece sempre que abro um novo jogo, um novo teste. Sempre.
E vou te passar o F12 quanto antes.
Inglês sei lá tava tudo em Ingles aqui fui no automatico. Mico bom!

**Comment by jptrrs** [comment]
Você já olhou se no cenário que vc tá usando tem alguma coisa feita de
madeira?

**Comment by sergiodinapoli** [comment]
Tive a brilhante idéia de abortar o QuickStart e gerar tudo do zero, ai deu certo.
