### ISSUE TITLE
Bubble inesperado, vindo do passado

### ISSUE THREAD

**Issue by sergiodinapoli** [jptrrs/SpeakUp#5]
Bom, vamos ver se estou fazendo algo útil.
Primeira coisa, o log.
Segunda coisa, o F12.
Isso tudo refere-se a uma imagem que nao te mando, pois vc nao quer kkk, que é: um balao completamente isolado no meio do mapa, sem razao de existir.
Como nasceu? Assim: eu tava testando e ja via algum comportamento esquisito (um interactiondef que tinha que ser usado como resposta, mas que surgiu do nada sem um "patches.xml" inicial.
Ai pensei: vou resetar o cenario. E gerei novo mapa e tal. Resultado: o balao do mapa anterior, ficou impresso no mapa novo. Um balao solitario, eternamente fixo, impossivel de tirar.
------------------------------------------------------------------------------------------------
RimWorld 1.2.2900 rev837
Verse.Log:Message(String, Boolean)
RimWorld.VersionControl:LogVersionNumber()
Verse.Root:CheckGlobalInit()
Verse.Root:Start()
Verse.Root_Entry:Start()

[HugsLib] version 8.0.1
Verse.Log:Message(String, Boolean)
HugsLib.Utils.ModLogger:Message(String, Object[])
HugsLib.HugsLibController:InitializeController()
HugsLib.HugsLibController:EarlyInitialize()
HugsLib.Core.HugsLibMod:.ctor(ModContentPack)
System.Reflection.MonoCMethod:InternalInvoke(Object, Object[], Exception&)
System.Reflection.MonoCMethod:InternalInvoke(Object, Object[])
System.Reflection.MonoCMethod:DoInvoke(Object, BindingFlags, Binder, Object[], CultureInfo)
System.Reflection.MonoCMethod:Invoke(BindingFlags, Binder, Object[], CultureInfo)
System.RuntimeType:CreateInstanceImpl(BindingFlags, Binder, Object[], CultureInfo, Object[], StackCrawlMark&)
System.Activator:CreateInstance(Type, BindingFlags, Binder, Object[], CultureInfo, Object[])
System.Activator:CreateInstance(Type, Object[])
Verse.LoadedModManager:CreateModClasses()
Verse.LoadedModManager:LoadAllActiveMods()
Verse.PlayDataLoader:DoPlayLoad()
Verse.PlayDataLoader:LoadAllPlayData(Boolean)
Verse.<>c:<Start>b__6_1()
Verse.LongEventHandler:RunEventFromAnotherThread(Action)
Verse.<>c:<UpdateCurrentAsynchronousEvent>b__27_0()
System.Threading.ThreadHelper:ThreadStart_Context(Object)
System.Threading.ExecutionContext:RunInternal(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object)
System.Threading.ThreadHelper:ThreadStart()

[Interaction Bubbles v1.7] Initialized
Verse.Log:Message(String, Boolean)
Bubbles.Mod:Log(String)
Bubbles.Mod:.cctor()
System.Object:__icall_wrapper_mono_generic_class_init(IntPtr)
Bubbles.Instance:.ctor(ModContentPack)
System.Reflection.MonoCMethod:InternalInvoke(Object, Object[], Exception&)
System.Reflection.MonoCMethod:InternalInvoke(Object, Object[])
System.Reflection.MonoCMethod:DoInvoke(Object, BindingFlags, Binder, Object[], CultureInfo)
System.Reflection.MonoCMethod:Invoke(BindingFlags, Binder, Object[], CultureInfo)
System.RuntimeType:CreateInstanceImpl(BindingFlags, Binder, Object[], CultureInfo, Object[], StackCrawlMark&)
System.Activator:CreateInstance(Type, BindingFlags, Binder, Object[], CultureInfo, Object[])
System.Activator:CreateInstance(Type, Object[])
Verse.LoadedModManager:CreateModClasses()
Verse.LoadedModManager:LoadAllActiveMods()
Verse.PlayDataLoader:DoPlayLoad()
Verse.PlayDataLoader:LoadAllPlayData(Boolean)
Verse.<>c:<Start>b__6_1()
Verse.LongEventHandler:RunEventFromAnotherThread(Action)
Verse.<>c:<UpdateCurrentAsynchronousEvent>b__27_0()
System.Threading.ThreadHelper:ThreadStart_Context(Object)
System.Threading.ExecutionContext:RunInternal(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object)
System.Threading.ThreadHelper:ThreadStart()

Key binding conflict: Dev_ChangeSelectedDebugAction and MainTab_Architect are both bound to Tab.
Verse.Log:Warning(String, Boolean)
Verse.KeyPrefsData:ErrorCheckOn(KeyBindingDef, BindingSlot)
Verse.KeyPrefsData:ErrorCheck()
Verse.KeyPrefs:Init()
Verse.PlayDataLoader:DoPlayLoad()
Verse.PlayDataLoader:LoadAllPlayData(Boolean)
Verse.<>c:<Start>b__6_1()
Verse.LongEventHandler:RunEventFromAnotherThread(Action)
Verse.<>c:<UpdateCurrentAsynchronousEvent>b__27_0()
System.Threading.ThreadHelper:ThreadStart_Context(Object)
System.Threading.ExecutionContext:RunInternal(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object)
System.Threading.ThreadHelper:ThreadStart()

Loaded file (Scenario) is from version 1.2.2753 rev712, we are running version 1.2.2900 rev837.
Verse.Log:Warning(String, Boolean)
Verse.ScribeMetaHeaderUtility:LoadGameDataHeader(ScribeHeaderMode, Boolean)
Verse.GameDataSaveLoader:TryLoadScenario(String, ScenarioCategory, Scenario&)
RimWorld.ScenarioFiles:RecacheData()
RimWorld.ScenarioLister:RecacheData()
RimWorld.ScenarioLister:RecacheIfDirty()
RimWorld.<AllScenarios>d__1:MoveNext()
System.Linq.Enumerable:TryGetFirst(IEnumerable`1, Func`2, Boolean&)
System.Linq.Enumerable:FirstOrDefault(IEnumerable`1, Func`2)
HugsLib.Quickstart.QuickstartController:TryGetScenarioByName(String)
HugsLib.Quickstart.QuickstartController:PrepareMapGeneration()
HugsLib.Quickstart.QuickstartController:InitateMapGeneration()
HugsLib.Quickstart.QuickstartController:InitiateQuickstart()
Verse.LongEventHandler:UpdateCurrentSynchronousEvent(Boolean&)
Verse.LongEventHandler:LongEventsUpdate(Boolean&)
Verse.Root:Verse.Root.Update_Patch1(Root)
Verse.Root_Entry:Update()

Could not load reference to Verse.ThingDef named WoodLog_Teak
Verse.Log:Error(String, Boolean)
Verse.ScribeExtractor:DefFromNode(XmlNode)
Verse.Scribe_Defs:Look(ThingDef&, String)
RimWorld.ScenPart_ThingCount:ExposeData()
Verse.ScribeExtractor:SaveableFromNode(XmlNode, Object[])
Verse.Scribe_Collections:Look(List`1&, Boolean, String, LookMode, Object[])
Verse.Scribe_Collections:Look(List`1&, String, LookMode, Object[])
RimWorld.Scenario:ExposeData()
Verse.ScribeExtractor:SaveableFromNode(XmlNode, Object[])
Verse.Scribe_Deep:Look(Scenario&, Boolean, String, Object[])
Verse.Scribe_Deep:Look(Scenario&, String, Object[])
Verse.GameDataSaveLoader:TryLoadScenario(String, ScenarioCategory, Scenario&)
RimWorld.ScenarioFiles:RecacheData()
RimWorld.ScenarioLister:RecacheData()
RimWorld.ScenarioLister:RecacheIfDirty()
RimWorld.<AllScenarios>d__1:MoveNext()
System.Linq.Enumerable:TryGetFirst(IEnumerable`1, Func`2, Boolean&)
System.Linq.Enumerable:FirstOrDefault(IEnumerable`1, Func`2)
HugsLib.Quickstart.QuickstartController:TryGetScenarioByName(String)
HugsLib.Quickstart.QuickstartController:PrepareMapGeneration()
HugsLib.Quickstart.QuickstartController:InitateMapGeneration()
HugsLib.Quickstart.QuickstartController:InitiateQuickstart()
Verse.LongEventHandler:UpdateCurrentSynchronousEvent(Boolean&)
Verse.LongEventHandler:LongEventsUpdate(Boolean&)
Verse.Root:Verse.Root.Update_Patch1(Root)
Verse.Root_Entry:Update()

Could not load reference to Verse.ThingDef named LumberOak
Verse.Log:Error(String, Boolean)
Verse.ScribeExtractor:DefFromNode(XmlNode)
Verse.Scribe_Defs:Look(ThingDef&, String)
RimWorld.ScenPart_ThingCount:ExposeData()
Verse.ScribeExtractor:SaveableFromNode(XmlNode, Object[])
Verse.Scribe_Collections:Look(List`1&, Boolean, String, LookMode, Object[])
Verse.Scribe_Collections:Look(List`1&, String, LookMode, Object[])
RimWorld.Scenario:ExposeData()
Verse.ScribeExtractor:SaveableFromNode(XmlNode, Object[])
Verse.Scribe_Deep:Look(Scenario&, Boolean, String, Object[])
Verse.Scribe_Deep:Look(Scenario&, String, Object[])
Verse.GameDataSaveLoader:TryLoadScenario(String, ScenarioCategory, Scenario&)
RimWorld.ScenarioFiles:RecacheData()
RimWorld.ScenarioLister:RecacheData()
RimWorld.ScenarioLister:RecacheIfDirty()
RimWorld.<AllScenarios>d__1:MoveNext()
System.Linq.Enumerable:TryGetFirst(IEnumerable`1, Func`2, Boolean&)
System.Linq.Enumerable:FirstOrDefault(IEnumerable`1, Func`2)
HugsLib.Quickstart.QuickstartController:TryGetScenarioByName(String)
HugsLib.Quickstart.QuickstartController:PrepareMapGeneration()
HugsLib.Quickstart.QuickstartController:InitateMapGeneration()
HugsLib.Quickstart.QuickstartController:InitiateQuickstart()
Verse.LongEventHandler:UpdateCurrentSynchronousEvent(Boolean&)
Verse.LongEventHandler:LongEventsUpdate(Boolean&)
Verse.Root:Verse.Root.Update_Patch1(Root)
Verse.Root_Entry:Update()

Could not load reference to Verse.ThingDef named WoodLog_Teak
Verse.Log:Error(String, Boolean)
Verse.ScribeExtractor:DefFromNode(XmlNode)
Verse.Scribe_Defs:Look(ThingDef&, String)
RimWorld.ScenPart_ThingCount:ExposeData()
Verse.ScribeExtractor:SaveableFromNode(XmlNode, Object[])
Verse.Scribe_Collections:Look(List`1&, Boolean, String, LookMode, Object[])
Verse.Scribe_Collections:Look(List`1&, String, LookMode, Object[])
RimWorld.Scenario:ExposeData()
Verse.ScribeExtractor:SaveableFromNode(XmlNode, Object[])
Verse.Scribe_Deep:Look(Scenario&, Boolean, String, Object[])
Verse.Scribe_Deep:Look(Scenario&, String, Object[])
Verse.GameDataSaveLoader:TryLoadScenario(String, ScenarioCategory, Scenario&)
RimWorld.ScenarioFiles:RecacheData()
RimWorld.ScenarioLister:RecacheData()
RimWorld.ScenarioLister:RecacheIfDirty()
RimWorld.<AllScenarios>d__1:MoveNext()
System.Linq.Enumerable:TryGetFirst(IEnumerable`1, Func`2, Boolean&)
System.Linq.Enumerable:FirstOrDefault(IEnumerable`1, Func`2)
HugsLib.Quickstart.QuickstartController:TryGetScenarioByName(String)
HugsLib.Quickstart.QuickstartController:PrepareMapGeneration()
HugsLib.Quickstart.QuickstartController:InitateMapGeneration()
HugsLib.Quickstart.QuickstartController:InitiateQuickstart()
Verse.LongEventHandler:UpdateCurrentSynchronousEvent(Boolean&)
Verse.LongEventHandler:LongEventsUpdate(Boolean&)
Verse.Root:Verse.Root.Update_Patch1(Root)
Verse.Root_Entry:Update()

Some ScenParts had null defs.
Verse.Log:Warning(String, Boolean)
RimWorld.Scenario:ExposeData()
Verse.PostLoadIniter:DoAllPostLoadInits()
Verse.ScribeLoader:FinalizeLoading()
Verse.GameDataSaveLoader:TryLoadScenario(String, ScenarioCategory, Scenario&)
RimWorld.ScenarioFiles:RecacheData()
RimWorld.ScenarioLister:RecacheData()
RimWorld.ScenarioLister:RecacheIfDirty()
RimWorld.<AllScenarios>d__1:MoveNext()
System.Linq.Enumerable:TryGetFirst(IEnumerable`1, Func`2, Boolean&)
System.Linq.Enumerable:FirstOrDefault(IEnumerable`1, Func`2)
HugsLib.Quickstart.QuickstartController:TryGetScenarioByName(String)
HugsLib.Quickstart.QuickstartController:PrepareMapGeneration()
HugsLib.Quickstart.QuickstartController:InitateMapGeneration()
HugsLib.Quickstart.QuickstartController:InitiateQuickstart()
Verse.LongEventHandler:UpdateCurrentSynchronousEvent(Boolean&)
Verse.LongEventHandler:LongEventsUpdate(Boolean&)
Verse.Root:Verse.Root.Update_Patch1(Root)
Verse.Root_Entry:Update()

[HugsLib] Quickstarter generating map with scenario: Crashlanded
Verse.Log:Message(String, Boolean)
HugsLib.Utils.ModLogger:Message(String, Object[])
HugsLib.Quickstart.QuickstartController:InitateMapGeneration()
HugsLib.Quickstart.QuickstartController:InitiateQuickstart()
Verse.LongEventHandler:UpdateCurrentSynchronousEvent(Boolean&)
Verse.LongEventHandler:LongEventsUpdate(Boolean&)
Verse.Root:Verse.Root.Update_Patch1(Root)
Verse.Root_Entry:Update()

[HugsLib] initializing SpeakUp
Verse.Log:Message(String, Boolean)
HugsLib.Utils.ModLogger:Message(String, Object[])
HugsLib.HugsLibController:EnumerateChildMods(Boolean)
HugsLib.HugsLibController:LoadReloadInitialize()
Verse.LongEventHandler:RunEventFromAnotherThread(Action)
Verse.<>c:<UpdateCurrentAsynchronousEvent>b__27_0()
System.Threading.ThreadHelper:ThreadStart_Context(Object)
System.Threading.ExecutionContext:RunInternal(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object)
System.Threading.ThreadHelper:ThreadStart()

Initializing new game with mods:
  - Ludeon.RimWorld
  - Ludeon.RimWorld.Royalty
  - brrainz.harmony
  - UnlimitedHugs.HugsLib
  - brrainz.cameraplus
  - Jaxe.Bubbles
  - Uuugggg.ListEverything
  - JPT.speakup
Verse.Log:Message(String, Boolean)
Verse.Game:InitNewGame()
Verse.<>c:<Start>b__1_2()
Verse.LongEventHandler:RunEventFromAnotherThread(Action)
Verse.<>c:<UpdateCurrentAsynchronousEvent>b__27_0()
System.Threading.ThreadHelper:ThreadStart_Context(Object)
System.Threading.ExecutionContext:RunInternal(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object)
System.Threading.ThreadHelper:ThreadStart()

[HugsLib] Quickstarter is loading saved game: Autosave-2
Verse.Log:Message(String, Boolean)
HugsLib.Utils.ModLogger:Message(String, Object[])
HugsLib.Quickstart.QuickstartController:InitateSaveLoading()
HugsLib.Quickstart.Dialog_QuickstartSettings:MakeSelectSaveButton(Listing_Standard, QuickstartSettings)
HugsLib.Quickstart.<>c__DisplayClass6_0:<DoWindowContents>b__0(Listing_Standard, Single)
HugsLib.Quickstart.Dialog_QuickstartSettings:MakeSubListing(Listing_Standard, Single, Single, Single, Single, Single, Action`2)
HugsLib.Quickstart.Dialog_QuickstartSettings:DoWindowContents(Rect)
Verse.Window:InnerWindowOnGUI(Int32)
UnityEngine.GUI:CallWindowDelegate(WindowFunction, Int32, Int32, GUISkin, Int32, Single, Single, GUIStyle)

Loading game from file Autosave-2 with mods:
  - Ludeon.RimWorld
  - Ludeon.RimWorld.Royalty
  - brrainz.harmony
  - UnlimitedHugs.HugsLib
  - brrainz.cameraplus
  - Jaxe.Bubbles
  - Uuugggg.ListEverything
  - JPT.speakup
Verse.Log:Message(String, Boolean)
Verse.SavedGameLoaderNow:LoadGameFromSaveFileNow(String)
Verse.<>c:<Start>b__1_1()
Verse.LongEventHandler:RunEventFromAnotherThread(Action)
Verse.<>c:<UpdateCurrentAsynchronousEvent>b__27_0()
System.Threading.ThreadHelper:ThreadStart_Context(Object)
System.Threading.ExecutionContext:RunInternal(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object)
System.Threading.ThreadHelper:ThreadStart()

[HugsLib] Quickstarter generating map with scenario: Crashlanded
Verse.Log:Message(String, Boolean)
HugsLib.Utils.ModLogger:Message(String, Object[])
HugsLib.Quickstart.QuickstartController:InitateMapGeneration()
HugsLib.Quickstart.Dialog_QuickstartSettings:MakeSelectScenarioButton(Listing_Standard, QuickstartSettings)
HugsLib.Quickstart.<>c__DisplayClass6_0:<DoWindowContents>b__1(Listing_Standard, Single)
HugsLib.Quickstart.Dialog_QuickstartSettings:MakeSubListing(Listing_Standard, Single, Single, Single, Single, Single, Action`2)
HugsLib.Quickstart.Dialog_QuickstartSettings:DoWindowContents(Rect)
Verse.Window:InnerWindowOnGUI(Int32)
UnityEngine.GUI:CallWindowDelegate(WindowFunction, Int32, Int32, GUISkin, Int32, Single, Single, GUIStyle)

Initializing new game with mods:
  - Ludeon.RimWorld
  - Ludeon.RimWorld.Royalty
  - brrainz.harmony
  - UnlimitedHugs.HugsLib
  - brrainz.cameraplus
  - Jaxe.Bubbles
  - Uuugggg.ListEverything
  - JPT.speakup
Verse.Log:Message(String, Boolean)
Verse.Game:InitNewGame()
Verse.<>c:<Start>b__1_2()
Verse.LongEventHandler:RunEventFromAnotherThread(Action)
Verse.<>c:<UpdateCurrentAsynchronousEvent>b__27_0()
System.Threading.ThreadHelper:ThreadStart_Context(Object)
System.Threading.ExecutionContext:RunInternal(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object)
System.Threading.ThreadHelper:ThreadStart()
-----------------------------------------------------------------------
Log uploaded on Tuesday, April 20, 2021, 8:23:07 PM
Loaded mods:
Core(Ludeon.RimWorld): (no assemblies)
Royalty(Ludeon.RimWorld.Royalty): (no assemblies)
Harmony(brrainz.harmony)[mv:1.0.4.0]: 0Harmony(2.0.2), HarmonyMod(1.0.4)
HugsLib(UnlimitedHugs.HugsLib)[ov:8.0.1]: 0Harmony(av:2.0.2,fv:1.2.0.1), HugsLib(av:1.0.0,fv:8.0.1)
Camera+(brrainz.cameraplus)[mv:2.1.2.0]: 0Harmony(2.0.2), CameraPlus(2.1.2)
Interaction Bubbles(Jaxe.Bubbles): Bubbles(1.7.0)
List Everything(Uuugggg.ListEverything): List_Everything(1.0.0)
SpeakUp(JPT.speakup): SpeakUp(av:0.3.0,fv:0.3.0)

Active Harmony patches:
BattleLog.Add: post: Bubbles.Patch.Verse_BattleLog_Add.Postfix
CameraDriver.ApplyPositionToGameObject: TRANS: CameraPlus.CameraDriver_ApplyPositionToGameObject_Patch.Transpiler
CameraDriver.CalculateCurInputDollyVect: post: CameraPlus.CameraDriver_CalculateCurInputDollyVect_Patch.Postfix
CameraDriver.Update: TRANS: CameraPlus.CameraDriver_Update_Patch.Transpiler
CameraDriver.get_CurrentViewRect: TRANS: CameraPlus.CameraDriver_CurrentViewRect_Patch.Transpiler
CameraDriver.get_CurrentZoom: PRE: CameraPlus.CameraDriver_CurrentZoom_Patch.Prefix
DebugWindowsOpener.DevToolStarterOnGUI: TRANS: HugsLib.Patches.DevToolStarterOnGUI_Patch.ExtendButtonsWindow
DebugWindowsOpener.DrawButtons: TRANS: HugsLib.Patches.DebugWindowsOpener_Patch.DrawAdditionalButtons
Dialog_Options.DoWindowContents: TRANS: HugsLib.Patches.Dialog_Options_Patch.ReplaceModOptionsButton
EditWindow_Log.DoMessagesListing: PRE: HugsLib.Patches.EditWindow_Log_Patch.ExtraLogWindowButtons
Game.DeinitAndRemoveMap: post: HugsLib.Patches.Game_DeinitAndRemoveMap_Patch.MapRemovalHook
Game.FillComponents: PRE: HugsLib.Patches.Game_FillComponents_Patch.GameInitializationHook
Game.FinalizeInit: post: HugsLib.Patches.Game_FinalizeInit_Patch.WorldLoadedHook, CameraPlus.Game_FinalizeInit_Patch.Postfix
GenMapUI.DrawPawnLabel: PRE: [10000]CameraPlus.GenMapUI_DrawPawnLabel_Patch.Prefix
GenMapUI.DrawThingLabel: PRE: [10000]CameraPlus.GenMapUI_DrawThingLabel_Patch.Prefix TRANS: CameraPlus.GenMapUI_DrawThingLabel_Patch.Transpiler
GrammarResolver.RandomPossiblyResolvableEntry: PRE: SpeakUp.GrammarResolver_RandomPossiblyResolvableEntry.Prefix post: SpeakUp.GrammarResolver_RandomPossiblyResolvableEntry.Postfix
GrammarResolver.Resolve: PRE: SpeakUp.GrammarResolver_Resolve.Prefix
GrammarResolver.RuleEntry.ValidateConstantConstraints: post: SpeakUp.RuleEntry_ValidateConstantConstraints.Postfix
GrammarResolver.TryResolveRecursive: PRE: SpeakUp.GrammarResolver_TryResolveRecursive.Prefix post: SpeakUp.GrammarResolver_TryResolveRecursive.Postfix
LanguageDatabase.SelectLanguage: PRE: HugsLib.Patches.LanguageDatabase_Patch.ForceRestartAfterLangChange
Map.ConstructComponents: post: HugsLib.Patches.Map_ConstructComponents_Patch.MapComponentsInitHook
Map.FinalizeInit: post: HugsLib.Patches.Map_FinalizeInit_Patch.MapLoadedHook
MapComponentUtility.MapGenerated: post: HugsLib.Patches.MapComponentUtility_MapGenerated_Patch.MapGeneratedHook
MapInterface.MapInterfaceOnGUI_BeforeMainTabs: post: Bubbles.Patch.RimWorld_MapInterface_MapInterfaceOnGUI_BeforeMainTabs.Postfix
MemoryUtility.ClearAllMapsAndWorld: PRE: Bubbles.Patch.Verse_Profile_MemoryUtility_ClearAllMapsAndWorld.Prefix
ModLister.RebuildModList: post: CrossPromotionModule.CrossPromotion.ModLister_RebuildModList_Postfix
ModsConfig.RestartFromChangedMods: PRE: HugsLib.Patches.ModsConfig_RestartFromChangedMods_Patch.QuickRestartInDevMode
MoteMaker.ThrowText: PRE: CameraPlus.MoteMaker_ThrowText_Patch.Prefix
Page_ModsConfig.DoWindowContents: TRANS: CrossPromotionModule.CrossPromotion.Page_ModsConfig_DoWindowContents_Transpiler
Page_ModsConfig.PostClose: post: CrossPromotionModule.CrossPromotion.Page_ModsConfig_PostClose_Postfix
PawnRenderer.RenderPawnAt: PRE: [10000]CameraPlus.PawnRenderer_RenderPawnAt_Patch.Prefix post: CameraPlus.PawnRenderer_RenderPawnAt_Patch.Postfix
PawnUIOverlay.DrawPawnGUIOverlay: PRE: [10000]CameraPlus.PawnUIOverlay_DrawPawnGUIOverlay_Patch.Prefix TRANS: CameraPlus.PawnUIOverlay_DrawPawnGUIOverlay_Patch.Transpiler
Pawn_InteractionsTracker.InteractionsTrackerTick: post: SpeakUp.Pawn_InteractionsTracker_InteractionsTrackerTick.Postfix
PlayDataLoader.DoPlayLoad: post: HugsLib.Patches.PlayDataLoader_Patch.InitModsHook
PlayLog.Add: post: Bubbles.Patch.Verse_PlayLog_Add.Postfix
PlayLogEntry_Interaction.ToGameStringFromPOV_Worker: PRE: SpeakUp.PlayLogEntry_Interaction_ToGameStringFromPOV_Worker.Prefix post: SpeakUp.PlayLogEntry_Interaction_ToGameStringFromPOV_Worker.Postfix
PlaySettings.DoPlaySettingsGlobalControls: post: Bubbles.Patch.RimWorld_PlaySettings_DoPlaySettingsGlobalControls.Postfix
Root.OnGUI: post: HugsLib.Patches.Root_OnGUI_Patch.OnGUIHookUnfiltered
Root.Update: post: HugsLib.Patches.Root_Patch.UpdateHook
Root_Play.SetupForQuickTestPlay: TRANS: HugsLib.Patches.RootPlay_TestPlay_Patch.InjectCustomQuickstartSettings
TickManager.DoSingleTick: post: SpeakUp.TickManager_DoSingleTick.Postfix
TimeControls.DoTimeControlsGUI: PRE: CameraPlus.TimeControls_DoTimeControlsGUI_Patch.Prefix
UIRoot.UIRootOnGUI: post: HugsLib.Patches.UIRoot_OnGUI_Patch.OnGUIHook
VersionControl.DrawInfoInCorner: post: HarmonyMod.VersionControl_DrawInfoInCorner_Patch.Postfix
WorkshopItems.Notify_Subscribed: post: CrossPromotionModule.CrossPromotion.WorkshopItems_Notify_Subscribed_Postfix
Harmony versions present: 2.0.4.0: Bubbles, JPT.speakup; 2.0.2.0: net.pardeike.rimworld.lib.harmony, net.pardeike.rimworld.mod.camera+, brrainz-crosspromotion; 2.0.0.8: UnlimitedHugs.HugsLib

Platform information: (hidden, use publishing options to include)

Log file contents:
Mono path[0] = '[Rimworld_dir]/RimWorldWin64_Data/Managed'
Mono config path = '[Rimworld_dir]/MonoBleedingEdge/etc'
Initialize engine version: 2019.2.17f1 (8e603399ca02)
[XR] Discovering subsystems at path [Rimworld_dir]/RimWorldWin64_Data/UnitySubsystems
GfxDevice: [Renderer information redacted]
Begin MonoManager ReloadAssembly
RimWorld 1.2.2900 rev837
[HugsLib] version 8.0.1
[Interaction Bubbles v1.7] Initialized
Key binding conflict: Dev_ChangeSelectedDebugAction and MainTab_Architect are both bound to Tab.
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

Loaded file (Scenario) is from version 1.2.2753 rev712, we are running version 1.2.2900 rev837.
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

Could not load reference to Verse.ThingDef named WoodLog_Teak
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

Could not load reference to Verse.ThingDef named LumberOak
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

Could not load reference to Verse.ThingDef named WoodLog_Teak
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

Some ScenParts had null defs.
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

[HugsLib] Quickstarter generating map with scenario: Crashlanded
[HugsLib] initializing SpeakUp
Unloading 5 Unused Serialized files (Serialized files now loaded: 1)

Unloading 52 unused Assets to reduce memory usage. Loaded Objects now: 10970.
Total: 115.673800 ms (FindLiveObjects: 0.779900 ms CreateObjectMapping: 0.398000 ms MarkObjects: 114.419300 ms  DeleteObjects: 0.076300 ms)

Initializing new game with mods:
  - Ludeon.RimWorld
  - Ludeon.RimWorld.Royalty
  - brrainz.harmony
  - UnlimitedHugs.HugsLib
  - brrainz.cameraplus
  - Jaxe.Bubbles
  - Uuugggg.ListEverything
  - JPT.speakup
Unloading 1 Unused Serialized files (Serialized files now loaded: 1)

Unloading 0 unused Assets to reduce memory usage. Loaded Objects now: 13910.
Total: 145.024600 ms (FindLiveObjects: 0.935900 ms CreateObjectMapping: 0.545200 ms MarkObjects: 143.481400 ms  DeleteObjects: 0.061800 ms)

[HugsLib] Quickstarter is loading saved game: Autosave-2
Unloading 3 Unused Serialized files (Serialized files now loaded: 1)

Unloading 35 unused Assets to reduce memory usage. Loaded Objects now: 14075.
Total: 155.040900 ms (FindLiveObjects: 1.392500 ms CreateObjectMapping: 0.586500 ms MarkObjects: 152.939400 ms  DeleteObjects: 0.122200 ms)

Loading game from file Autosave-2 with mods:
  - Ludeon.RimWorld
  - Ludeon.RimWorld.Royalty
  - brrainz.harmony
  - UnlimitedHugs.HugsLib
  - brrainz.cameraplus
  - Jaxe.Bubbles
  - Uuugggg.ListEverything
  - JPT.speakup
Unloading 0 Unused Serialized files (Serialized files now loaded: 1)

Unloading 0 unused Assets to reduce memory usage. Loaded Objects now: 17733.
Total: 197.761300 ms (FindLiveObjects: 1.144800 ms CreateObjectMapping: 0.686800 ms MarkObjects: 195.874100 ms  DeleteObjects: 0.055300 ms)

[HugsLib] Quickstarter generating map with scenario: Crashlanded
Unloading 3 Unused Serialized files (Serialized files now loaded: 1)

Unloading 6 unused Assets to reduce memory usage. Loaded Objects now: 17823.
Total: 209.157100 ms (FindLiveObjects: 1.253800 ms CreateObjectMapping: 0.729300 ms MarkObjects: 207.067900 ms  DeleteObjects: 0.105800 ms)

Initializing new game with mods:
  - Ludeon.RimWorld
  - Ludeon.RimWorld.Royalty
  - brrainz.harmony
  - UnlimitedHugs.HugsLib
  - brrainz.cameraplus
  - Jaxe.Bubbles
  - Uuugggg.ListEverything
  - JPT.speakup
Unloading 0 Unused Serialized files (Serialized files now loaded: 1)

Unloading 0 unused Assets to reduce memory usage. Loaded Objects now: 22050.
Total: 243.120000 ms (FindLiveObjects: 1.386100 ms CreateObjectMapping: 0.937500 ms MarkObjects: 240.719000 ms  DeleteObjects: 0.077000 ms)

**Comment by jptrrs** [comment]
Viva! Um log!!! É isso que precisamos, parabéns!
Mas....
Não temos nenhuma interface com o Interaction Bubbles, lembra? Não tem nada no nosso código que gere balões, que coloque ou o apague eles da tela. Enfim, não tocamos no Bubbles! Esse é um problema para o Jaxe.
