### ISSUE TITLE
Comportamento imprevisto de " != "

### ISSUE THREAD

**Issue by sergiodinapoli** [jptrrs/SpeakUp#8]
Quando escrevo 
<li>r_logentry(INITIATOR_trait!=undergrounder)->Nao sou undergrounder!</li>

na minha cabeça tem:
o código vai checar todos os traits do pawn e se nenhum deles é undergrounder, o test passa.

Mas pelo que entendi acontece isto:
o código vai selecionar um trait aleatorio do pawn e se este, por acaso, nao for undergrounder, o test passa.

Obviamente , se eu acertei, é um comportamento inesperado e pouco útil do operador NOT.

Seria - se eu acertei na minha análise - possível entao corrigir isto? Pois é quase primordial poder soltar frases, desde que um pawn não tenha um determinado trait (ou thought até) na lista de traits dele.

**Comment by sergiodinapoli** [comment]
Talvez, até para deixar o processamento de dados mais leve, seja interessante tentar trocar
INITIATOR_trait==undergrounder [que puxa um trait aleatoriamente e checa se este equivale a um trait especificado]

com algo do tipo:
INITIATOR_hastrait==undergrounder [que checa se aquele pawn tem o trait especificado]
e o associado
INITIATOR_hastrait!=undergrounder

Acho que faria mais sentido e ajudaria os colaboradores a escrever melhor as InteractionDefs.

E também acho que já tenha algo meio pronto, pois o jogo já precisa dessa função para algumas funcionalidades. :-)

**Comment by sergiodinapoli** [comment]
Montei toda uma série de diálogos para thoughtLabel de "Need beauty". São 6 labels.
Fiz toda uma matriz de texto e tal, mas... de novo mesmo problema:
thoughtLabel == X nao confirma se o Pawn tem aquele thought_Label e sim pega um trait random dele e vê se este é igual ao especifiquei.
Ou seja é possível que um pawn tenha um thoughtLabel ==ugly environment , mas ele não ser selecionado ao acaso. Mas meu texto se baseia no fato que o pawn tenha aquele "ugly environment".
Se o pawn tem 10 thoughts, inclusive o "ugly environment", a chance deste ser pego no random é bem baixa. 
Eu nao preciso puxar um thought random do pawn, eu preciso saber se o pawn possui ou nao o thoughtLabel "ugly environment". Puxar um thought random pode ser util em certos casos, mas saber se aquele thoughtLabel esta' entre que um pawn tem, é primordial.

Enfim - acho que torna-se necessário implementar o "hasLabel==ugly environment" para poder montar os diálogos corretamente.

**Comment by jptrrs** [comment]
Fiz essa InteractionDef para testar

```
<InteractionDef ParentName="SpeakUpReply">
  <defName>TiraTeima</defName>
  <label>tira-teima</label>
  <logRulesInitiator>
    <rulesStrings>
      <li>r_logentry(priority=0)->Nao sou undergrounder!</li>
      <li>r_logentry(priority=1,INITIATOR_trait==undergrounder)->Eu sou subterrâneo.</li>
    </rulesStrings>
  </logRulesInitiator>
</InteractionDef>
```

E forcei dois pawns, sendo um undergrounder, a interagir com ela. Eis o resultado:
	
![20210426035354_1](https://user-images.githubusercontent.com/47060670/116041359-80de3d00-a643-11eb-8ed3-cc0b17a29472.jpg)

Como você pode ver ali do lado, as duas traits do nosso amigo subterrâneo foram sim selecionadas:

> INITIATOR_trait: undergrounder
> INITIATOR_trait: nimble

E o sistema definiu corretamente que era o caso de usar a fala com prioridade mais alta, já que, sendo undergrounder, ele atendia a condição.

Já para o outro sujeito, quando eu forcei a interação para ele, a resolução saiu assim: (resumida)

> FAILED validating constraints for r_logentry:
> "INITIATOR_trait equal undergrounder"
> The rule text is "r_logentry → Eu sou subterrâneo.".
> ...
> INITIATOR_trait: kind
> INITIATOR_trait: fast learner
> INITIATOR_trait: beautiful
> ...

No caso dele, nenhuma trait satisfez a condição, então o sistema foi obrigado a selecionar a fala com menor prioridade.

Agora, se você inverter as condições entre as falas e colocar: 
```
<li>r_logentry(priority=1,INITIATOR_trait!=undergrounder)->Nao sou undergrounder!</li>
<li>r_logentry(priority=0)->Eu sou subterrâneo.</li>
```
Aí todos os dois vão dizer "Nao sou undergrounder!"... Claro! Porque o nosso undergrounder tem, lembre-se, duas traits: undergrounder e nimble. E pelo menos uma delas vai liberar a primeira fala.

Acho que está claro que a seleção de traits NÃO É aleatória, certo? 
O problema é que vc está esperando que o operador faça uma coisa que ele não faz. Vou tentar sintetizar...
O que a condição faz, seja ela um ==, um >= ou um !=, é assinalar, linha a linha, se aquela fala é valida ou não. Para isso, cada linha é confrontada com todos os parametros disponíveis. No caso de um parâmetro que tem múltiplos valores possíveis, como as traits, o sistema vai testar um por um para ver se ele atende à condição ou não. Assim, A pode passar no teste enquanto B levaria bomba. O lance é que assim que um parametro der match com a condição, aquela condição é considerada satisfeita, independente dos demais. Portanto, se a condição "trait != undergrounder" atende à primeira trait mas falha na segunda, o resultado ainda é "deu certo".
Quando todas as condições colocadas entre parentesis foram testadas e deram certo, então aquela fala é marcada como válida. Em um segundo momento, o sistema pega todas as falas válidas e seleciona uma delas, aleatoriamente ou seguindo as prioridades que houverem. Mas nesse momento da escolha, é bom reforçar, as condições já foram testadas e **não mandam mais em nada.** Então também não dá para esperar que a fala exclusiva para undergrounders tenha mais chance do que outras que são igualmente válidas.
A função que faz esse processamento é [essa aqui](https://github.com/jptrrs/SpeakUp/blob/581f5a4df590d1adb8c50f735195ea8ba976f1b0/SpeakUp/HarmonyPatches/RuleEntry_ValidateConstantConstraints.cs#L40), se tiver curiosidade

A mesma coisa vale para os pensamentos. Do mesmo relatório de antes:

> INITIATOR_thoughtDefName: NewColonyOptimism
> INITIATOR_thoughtDefName: AteWithoutTable
> INITIATOR_thoughtDefName: SleepDisturbed
> INITIATOR_thoughtDefName: SleptOnGround
> INITIATOR_thoughtDefName: SleptInCold
> INITIATOR_thoughtDefName: Expectations
> INITIATOR_thoughtDefName: NeedJoy
> INITIATOR_thoughtDefName: NeedComfort
> INITIATOR_thoughtDefName: NeedBeauty
> INITIATOR_thoughtLabel: initial optimism
> INITIATOR_thoughtLabel: ate without table
> INITIATOR_thoughtLabel: disturbed sleep
> INITIATOR_thoughtLabel: slept on ground
> INITIATOR_thoughtLabel: slept in the cold
> INITIATOR_thoughtLabel: extremely low expectations
> INITIATOR_thoughtLabel: recreation fully satisfied
> INITIATOR_thoughtLabel: uncomfortable
> INITIATOR_thoughtLabel: unsightly environment

Lembre que a gente resolveu colocar o _thoughtDefName para facilitar colocar em condições, já que o INITIATOR_thoughtLabel requer que você digite tudo exatamente igual, com todos os espaços... Mas considerando o que eu expliquei, vamos ver o que vc tá com dificuldade:

>Ou seja é possível que um pawn tenha um thoughtLabel ==ugly environment , mas ele não ser selecionado ao acaso. Mas meu texto se baseia no fato que o pawn tenha aquele "ugly environment".

Se você tem uma frase amarrada à "thoughtLabel ==ugly environment", o sistema deveria testar todos os "thoughtLabel" em busca de um "ugly environment". Se achar um que bate, a frase é válida. Mas daí a ela ser selecionada, são outros quinhentos... Porque pode ser que  outras frases também estejam valendo, mesmo que sejam mais sem graça.

No geral, estou com a impressão que é mais uma questão mais de cercar a bola corretamente para ela correr pro lado certo do que de criar mais regras pro jogo...

**Comment by jptrrs** [comment]
>O lance é que assim que um parametro der match com a condição, aquela condição é considerada satisfeita, independente dos demais."
>
>Acho que o nucleo do caos é aqui.

Bem, é assim que o sistema existente funciona. Observe que minha função é apenas uma ligeira modificação da original do Tynan. Para mudar esse funcionamento ela teria que ser re-escrita.

**Comment by sergiodinapoli** [comment]
Primeiramente obrigado por um texto de resposta tão grande. 

Como se trata de algo primordial, acho bom te escrever uma resposta para testar se entendi a parada primordial (com pseudo-code). Por favor caso eu escrever algo errado/equivocado me avise. E se eu acertar tudo, aplauda minha grande mente! :-D

Eu boto 3 linhas:

linha1(beleza==lindo)->Sou foda.
linha2(beleza!=lindo)->Sou lixo.
linha3->Sou o que sou.

Essas 3 linhas sao escolhidas random, pois têm a mesma priority (cujo default imagino seja zero).

Suponhamos um pawn que seja: lindo, alto e chato.

Se o diceroll for pra linha1, funciona legal.
Se o diceroll for pra linha3, simplesmente o pawn falara' "Sou o que sou" e pronto, afinal linha3 nao tem condiçoes.

Foquemos agora na linha2:
1) checa o primeiro trait, ve que temos "lindo" --> FAILED
2) checa o segundo trait, ve que temos "alto" --> SUCCESS
3) checa o 3° trait, ve que temos "chato" --> SUCCESS
Pronto. O pawn é sim lindo, mas é tido como feio. E temos um problema.

Vamos tentar então desse jeito:
linha1(priority=1,beleza==lindo)->Sou foda.
linha2(beleza!=lindo)->Sou lixo.
linha3->Sou o que sou.

Aqui a linha1 é escolhida com certeza, pois é a unica com prioridade 1. Se houvesse outra com prioridade 1, ai sim ia ter de novo um papo random. Mas agora é certeza. Linha1 primeiro!
E assim sendo, tudo funciona, pois nunca chegaremos na polêmica linha2.

E se o cara nao tiver "lindo"?
Ai a linha1 - prioritária - vai ter so FAILED. Nenhum trait == lindo.
Ai é diceroll entre linha2 e linha3.
Linha3 boazinha, OK. Pode ser.

Se diceroll preferir linha2, vai ter apenas SUCCESS. E ai o cara é tido como nao lindo, conforme esperado.

Nisso tudo, nao colocando a linha3 boazinha, teríamos sempre que garantir uma saída válida pro diceroll, ou a gente tem um "ERR: pawn".

Nesse caso, tirando a linha3 estamos tranquilos: pois se o cara tem "lindo", vai dar certo a linha1 sempre. E se o cara nao tem "lindo" vai dar certo a linha2 sempre. E como o cara ou tem ou nao tem "lindo", cobrimos todas as possibilidades.

Conclusão: para ser feliz nessa vida, toda vez que houver um "!=" temos que botar um "priority=1" no equivalente caso "==".
É isso mesmo, tudo que escrevi?

**Comment by sergiodinapoli** [comment]
E pelo que estudei aqui... parece que o "!=" basicamente é inútil, pois basta usar "priority" e ser feliz... ?

No exemplo acima: priority 1 manda. Se o cara tiver "lindo", SUCCESS. Se aquela linha de priority alta falhar, podemos concluir que o cara nao tem "lindo". Ou seja:
qualquer linha com prioridade inferior, equivale à garantia de que beleza!=lindo .

**Comment by jptrrs** [comment]
A princípio sim, tá certo. Como tudo na vida tem que testar, mas acho que sua conclusão está certa sim.
Só a ordem em que as coisas acontecem que não sei se ficou clara... o "diceroll" é só no fim. O processamento é assim:

1.  Entram as linhas:
linha0(priority=5,altura==baixo)->Sou tampinha.
linha1(priority=1,beleza==lindo)->Sou foda.
linha2(beleza!=lindo)->Sou lixo.
linha3->Sou o que sou.

2. Linhas são testadas com as condições dadas (considerando o pawn lindo, alto e chato).
linha 0: FAIL (eliminada)
linha 1: OK
linha 2: Ok
linha 3: OK

3. As linhas remanescente são sorteadas por prioridade e a maior é escolhida
linha1: 1 (escolhida)
linha2: 0
linha3: 0

Obs.1: A linha 0 que eu acrescentei ao seu exemplo não aparece mesmo tendo prioridade mais alta. Isso porque ela foi eliminada na segunda etapa.

Obs.2: SE o sujeito fosse feio e ficássemos entre as linhas 2 e 3, aí sim haveria uma "rolagem de dados". MAS, se essas linhas tivessem não prioridade, mas **probabilidade** (p=x), aí esses números ainda afetariam o resultado dos dados. Ou seja:  a escolha totalmente aleatória é apenas o último recurso!!!

Obs.3: Note que se a linha 2 fosse apenas "linha2->Sou lixo.", sem condição nenhuma, o resultado seria o mesmo, já que os pawns "lindos" sempre cairiam na linha 1 pela prioridade. Ou seja, não tem porquê usar o != nesse caso!

**Comment by jptrrs** [comment]
Obs.4: Tenho quase certeza que as linhas podem ter mais de uma condição. Você poderia escrever:
```
linha1(beleza==lindo,altura==alto)->Eu sou foda!
linha2(beleza==lindo,altura==alto,trait==modesto,p=10)->Deixa disso!
linha3->Sou o que sou.
```
E um pawn que fosse lindo, alto e modesto dificilmente falaria "Eu sou foda" ou "Sou o que sou", mas também não seria impossível.

**Comment by jptrrs** [comment]
> 
> 
> E pelo que estudei aqui... parece que o "!=" basicamente é inútil, pois basta usar "priority" e ser feliz... ?
> 
> No exemplo acima: priority 1 manda. Se o cara tiver "lindo", SUCCESS. Se aquela linha de priority alta falhar, podemos concluir que o cara nao tem "lindo". Ou seja:
> qualquer linha com prioridade inferior, equivale à garantia de que beleza!=lindo .

Sim, a mesma coisa que eu escrevi na Obs.3. 
Mas isso não significa que o != é de todo inútil, apenas que em uma situação com multiplos parametros que tem o mesmo nome (lembre-se que o jogo não foi feito para isso) ele não serve para eliminar uma opção. Já o ==, sim, é capaz de eliminar opções ao buscar por uma específica. 
Mas ele pode ser muito útil para testar parametros normais, por exemplo:

`linha(RECIPIENT_bestSkill!=shooting)->Você precisa melhorar sua pontaria!`

**Comment by sergiodinapoli** [comment]
Muito interessante essa investigação :-).
Eu acho que já entendo o esquema e agora que sei como funciona, dá para aprontar sem medo.
